Fixes

diff --git a/circleci/Dockerfile b/circleci/Dockerfile
--- a/circleci/Dockerfile
+++ b/circleci/Dockerfile
@@ -14,9 +14,9 @@ COPY .bashrc /root/
 ENV NVM_VERSION 0.33.5
 ENV NVM_DIR /root/.nvm
 # NVM is failing with -e option
-RUN echo '\n# Failsafe NVM activation\nset +e' >> /root/.bashrc
+RUN echo -e '\n# Failsafe NVM activation\nset +e' >> /root/.bashrc
 RUN curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | bash
-RUN echo '\nset -e' >> /root/.bashrc
+RUN echo -e '\nset -e' >> /root/.bashrc
 
 # Upgrade to latest virtualenv version
 RUN pip3 install -U virtualenv
